"""empty message

Revision ID: 165fd3c42c48
Revises: 
Create Date: 2021-08-24 11:07:24.462587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '165fd3c42c48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ListItems_id', table_name='ListItems')
    op.drop_index('ix_ListItems_name', table_name='ListItems')
    op.drop_table('ListItems')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ListItems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ListItems_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('date_added', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ListItems_pkey')
    )
    op.create_index('ix_ListItems_name', 'ListItems', ['name'], unique=False)
    op.create_index('ix_ListItems_id', 'ListItems', ['id'], unique=False)
    # ### end Alembic commands ###
