version: "3.5"
services:
  frontend_app:
    build: .
  
    ports:
      - 6543:6543
    command: bash start.sh
    restart: always
networks:
  default:
    external: true
    name: flaskapi_backend
