version: "3.5"
services:
  api:
    build: .
    depends_on:
      - db
    environment:
      STAGE: test
      FLASK_APP: app.main:app
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://siyavula:siyavula123@db/siyavula_db
    env_file:
      - ./.env
    networks:
      - backend

    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always


  db:
    environment:
      POSTGRES_USER: siyavula
      POSTGRES_PASSWORD: siyavula123
      POSTGRES_DB: siyavula_db
    image: postgres:latest
    networks:
      - backend
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
networks:
  backend:
      external: false
      driver: bridge